name: qawolf
on:
  push:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  test:
    name: ${{ matrix.browser }}
    runs-on: ubuntu-18.04
    
    strategy:
      matrix: 
        browser: [chromium, firefox]

    steps:
      # - uses: khan/pull-request-comment-trigger@master
      #   id: check
      #   with:
      #     trigger: 'run tests'
      #     reaction: rocket
      #   env:
      #     GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      # - run: 'echo Found it!'
      #   if: steps.check.outputs.triggered == 'true'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
        # if: steps.check.outputs.triggered == 'true'
      # - name: Start local server
      #   run: npm run start & npx wait-on http://localhost:3000
      - run: npx qawolf test --headless
        # if: steps.check.outputs.triggered == 'true'
        env:
          # configure tests with environment variables
          FFMPEG_PATH: /usr/bin/ffmpeg # for recording video
          BASE_URL: https://spacex-ships.now.sh
          QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts
          QAW_BROWSER: ${{ matrix.browser }}
          # you can also use GitHub secrets for environment variables
          # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
          # LOGIN_PASSWORD: ${{ secrets.PASSWORD }}
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf-${{ matrix.browser }}
          path: ${{ github.workspace }}/artifacts
  report:
    name: Report
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - name: List artifacts
        run: ls ${{ github.workspace }}/artifacts